services:
  bot:
    build: .
    volumes:
      - type: bind
        source: ./.env
        target: /opt/app/.env
  postgres:
    image: "postgres:17"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
volumes:
  pgdata:
    driver: local
